version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      build:
        docker:
          - image: cimg/openjdk:15.0.0-node
        steps:
          - checkout
          - run: java --version