version: 2.1

executors:
  java-version:
    docker:
      - image: cimg/openjdk:15.0.0

orbs:
  maven: circleci/maven@1.0.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results